# Generated by Django 4.2.1 on 2023-05-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsupplier',
            old_name='bussiness_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='bussiness_name',
            new_name='business_name',
        ),
    ]
